# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 875)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 6)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_enable = QtWidgets.QWidget(self.centralwidget)
        self.widget_enable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_enable.setAutoFillBackground(True)
        self.widget_enable.setObjectName("widget_enable")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget_enable)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.groupBox_15 = QtWidgets.QGroupBox(self.widget_enable)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.PB_main_enableCamera = QtWidgets.QPushButton(self.groupBox_15)
        self.PB_main_enableCamera.setMinimumSize(QtCore.QSize(60, 30))
        self.PB_main_enableCamera.setMaximumSize(QtCore.QSize(60, 16777215))
        self.PB_main_enableCamera.setCheckable(True)
        self.PB_main_enableCamera.setObjectName("PB_main_enableCamera")
        self.gridLayout_27.addWidget(self.PB_main_enableCamera, 0, 6, 1, 1)
        self.PB_main_enableRobot = QtWidgets.QPushButton(self.groupBox_15)
        self.PB_main_enableRobot.setMinimumSize(QtCore.QSize(60, 30))
        self.PB_main_enableRobot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.PB_main_enableRobot.setCheckable(True)
        self.PB_main_enableRobot.setObjectName("PB_main_enableRobot")
        self.gridLayout_27.addWidget(self.PB_main_enableRobot, 0, 4, 1, 1)
        self.PB_main_enableMainhand = QtWidgets.QPushButton(self.groupBox_15)
        self.PB_main_enableMainhand.setMinimumSize(QtCore.QSize(60, 30))
        self.PB_main_enableMainhand.setMaximumSize(QtCore.QSize(60, 16777215))
        self.PB_main_enableMainhand.setCheckable(True)
        self.PB_main_enableMainhand.setObjectName("PB_main_enableMainhand")
        self.gridLayout_27.addWidget(self.PB_main_enableMainhand, 0, 8, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_15)
        self.label_24.setObjectName("label_24")
        self.gridLayout_27.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_15)
        self.label_25.setObjectName("label_25")
        self.gridLayout_27.addWidget(self.label_25, 0, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_15)
        self.label_26.setObjectName("label_26")
        self.gridLayout_27.addWidget(self.label_26, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem, 0, 9, 1, 1)
        self.gridLayout_26.addWidget(self.groupBox_15, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_enable, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEditLog = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.textEditLog.setFont(font)
        self.textEditLog.setReadOnly(True)
        self.textEditLog.setObjectName("textEditLog")
        self.gridLayout_2.addWidget(self.textEditLog, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_panel = QtWidgets.QWidget()
        self.tab_panel.setObjectName("tab_panel")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_panel)
        self.gridLayout_22.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.GB_main_debug = QtWidgets.QGroupBox(self.tab_panel)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.GB_main_debug.setFont(font)
        self.GB_main_debug.setTitle("")
        self.GB_main_debug.setObjectName("GB_main_debug")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.GB_main_debug)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget_control = QtWidgets.QTabWidget(self.GB_main_debug)
        self.tabWidget_control.setObjectName("tabWidget_control")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_control)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_control)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_select = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_select.setObjectName("groupBox_select")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_select)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.checkB_show_img = QtWidgets.QCheckBox(self.groupBox_select)
        self.checkB_show_img.setObjectName("checkB_show_img")
        self.gridLayout_21.addWidget(self.checkB_show_img, 2, 0, 1, 1)
        self.checkB_sensor_protection = QtWidgets.QCheckBox(self.groupBox_select)
        self.checkB_sensor_protection.setObjectName("checkB_sensor_protection")
        self.gridLayout_21.addWidget(self.checkB_sensor_protection, 1, 0, 1, 1)
        self.checkB_robot_falling_protection = QtWidgets.QCheckBox(self.groupBox_select)
        self.checkB_robot_falling_protection.setObjectName("checkB_robot_falling_protection")
        self.gridLayout_21.addWidget(self.checkB_robot_falling_protection, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_select, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.LE_task_name = QtWidgets.QLineEdit(self.groupBox)
        self.LE_task_name.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_task_name.setObjectName("LE_task_name")
        self.gridLayout.addWidget(self.LE_task_name, 0, 1, 1, 1)
        self.PB_main_start = QtWidgets.QPushButton(self.groupBox)
        self.PB_main_start.setCheckable(False)
        self.PB_main_start.setObjectName("PB_main_start")
        self.gridLayout.addWidget(self.PB_main_start, 1, 0, 1, 1)
        self.PB_main_stop = QtWidgets.QPushButton(self.groupBox)
        self.PB_main_stop.setCheckable(False)
        self.PB_main_stop.setObjectName("PB_main_stop")
        self.gridLayout.addWidget(self.PB_main_stop, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout_16.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.tabWidget_control.addTab(self.tab_control, "")
        self.tab_debug = QtWidgets.QWidget()
        self.tab_debug.setObjectName("tab_debug")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_debug)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_debug)
        self.groupBox_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_29.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.label_32 = QtWidgets.QLabel(self.groupBox_17)
        self.label_32.setMinimumSize(QtCore.QSize(85, 25))
        self.label_32.setMaximumSize(QtCore.QSize(69, 60))
        self.label_32.setObjectName("label_32")
        self.gridLayout_29.addWidget(self.label_32, 0, 0, 1, 1)
        self.CB_debug_robot_light = QtWidgets.QComboBox(self.groupBox_17)
        self.CB_debug_robot_light.setMinimumSize(QtCore.QSize(0, 25))
        self.CB_debug_robot_light.setMaximumSize(QtCore.QSize(16777215, 60))
        self.CB_debug_robot_light.setObjectName("CB_debug_robot_light")
        self.CB_debug_robot_light.addItem("")
        self.CB_debug_robot_light.addItem("")
        self.CB_debug_robot_light.addItem("")
        self.CB_debug_robot_light.addItem("")
        self.gridLayout_29.addWidget(self.CB_debug_robot_light, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_17)
        self.label_37.setMinimumSize(QtCore.QSize(85, 25))
        self.label_37.setMaximumSize(QtCore.QSize(69, 60))
        self.label_37.setObjectName("label_37")
        self.gridLayout_29.addWidget(self.label_37, 1, 0, 1, 1)
        self.PB_debug_robot_light = QtWidgets.QPushButton(self.groupBox_17)
        self.PB_debug_robot_light.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_debug_robot_light.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PB_debug_robot_light.setFont(font)
        self.PB_debug_robot_light.setObjectName("PB_debug_robot_light")
        self.gridLayout_29.addWidget(self.PB_debug_robot_light, 1, 2, 1, 1)
        self.PB_debug_robot_getangle = QtWidgets.QPushButton(self.groupBox_17)
        self.PB_debug_robot_getangle.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_debug_robot_getangle.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PB_debug_robot_getangle.setFont(font)
        self.PB_debug_robot_getangle.setObjectName("PB_debug_robot_getangle")
        self.gridLayout_29.addWidget(self.PB_debug_robot_getangle, 0, 1, 1, 2)
        self.gridLayout_29.setColumnStretch(0, 1)
        self.gridLayout_29.setColumnStretch(1, 1)
        self.gridLayout_29.setColumnStretch(2, 1)
        self.gridLayout_6.addWidget(self.groupBox_17, 0, 0, 1, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_debug)
        self.groupBox_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_30.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_30 = QtWidgets.QLabel(self.groupBox_18)
        self.label_30.setMinimumSize(QtCore.QSize(85, 25))
        self.label_30.setMaximumSize(QtCore.QSize(69, 60))
        self.label_30.setObjectName("label_30")
        self.gridLayout_30.addWidget(self.label_30, 0, 0, 1, 1)
        self.PB_debug_gripper_control = QtWidgets.QPushButton(self.groupBox_18)
        self.PB_debug_gripper_control.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_debug_gripper_control.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PB_debug_gripper_control.setFont(font)
        self.PB_debug_gripper_control.setCheckable(True)
        self.PB_debug_gripper_control.setObjectName("PB_debug_gripper_control")
        self.gridLayout_30.addWidget(self.PB_debug_gripper_control, 0, 1, 1, 1)
        self.gridLayout_30.setColumnStretch(0, 1)
        self.gridLayout_30.setColumnStretch(1, 1)
        self.gridLayout_6.addWidget(self.groupBox_18, 1, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_debug)
        self.groupBox_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.PB_debug_cam_search = QtWidgets.QPushButton(self.groupBox_19)
        self.PB_debug_cam_search.setMinimumSize(QtCore.QSize(85, 25))
        self.PB_debug_cam_search.setMaximumSize(QtCore.QSize(69, 60))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PB_debug_cam_search.setFont(font)
        self.PB_debug_cam_search.setObjectName("PB_debug_cam_search")
        self.gridLayout_9.addWidget(self.PB_debug_cam_search, 0, 0, 1, 1)
        self.CB_debug_cam_ids = QtWidgets.QComboBox(self.groupBox_19)
        self.CB_debug_cam_ids.setMinimumSize(QtCore.QSize(0, 25))
        self.CB_debug_cam_ids.setMaximumSize(QtCore.QSize(16777215, 60))
        self.CB_debug_cam_ids.setObjectName("CB_debug_cam_ids")
        self.gridLayout_9.addWidget(self.CB_debug_cam_ids, 0, 1, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.groupBox_19)
        self.label_31.setMinimumSize(QtCore.QSize(85, 25))
        self.label_31.setMaximumSize(QtCore.QSize(69, 60))
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 1, 0, 1, 1)
        self.CB_debug_cam_which = QtWidgets.QComboBox(self.groupBox_19)
        self.CB_debug_cam_which.setMinimumSize(QtCore.QSize(0, 25))
        self.CB_debug_cam_which.setMaximumSize(QtCore.QSize(16777215, 60))
        self.CB_debug_cam_which.setObjectName("CB_debug_cam_which")
        self.gridLayout_9.addWidget(self.CB_debug_cam_which, 1, 1, 1, 1)
        self.PB_debug_cam_confirm = QtWidgets.QPushButton(self.groupBox_19)
        self.PB_debug_cam_confirm.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_debug_cam_confirm.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PB_debug_cam_confirm.setFont(font)
        self.PB_debug_cam_confirm.setObjectName("PB_debug_cam_confirm")
        self.gridLayout_9.addWidget(self.PB_debug_cam_confirm, 1, 2, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_9.setColumnStretch(1, 1)
        self.gridLayout_9.setColumnStretch(2, 1)
        self.gridLayout_6.addWidget(self.groupBox_19, 2, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_debug)
        self.groupBox_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_34.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.PB_debug_calibration_confirm = QtWidgets.QPushButton(self.groupBox_20)
        self.PB_debug_calibration_confirm.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_debug_calibration_confirm.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PB_debug_calibration_confirm.setFont(font)
        self.PB_debug_calibration_confirm.setCheckable(False)
        self.PB_debug_calibration_confirm.setObjectName("PB_debug_calibration_confirm")
        self.gridLayout_34.addWidget(self.PB_debug_calibration_confirm, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_20)
        self.label_38.setMinimumSize(QtCore.QSize(85, 25))
        self.label_38.setMaximumSize(QtCore.QSize(85, 60))
        self.label_38.setObjectName("label_38")
        self.gridLayout_34.addWidget(self.label_38, 0, 0, 1, 1)
        self.gridLayout_34.setColumnStretch(0, 1)
        self.gridLayout_34.setColumnStretch(1, 1)
        self.gridLayout_6.addWidget(self.groupBox_20, 3, 0, 1, 1)
        self.tabWidget_control.addTab(self.tab_debug, "")
        self.gridLayout_15.addWidget(self.tabWidget_control, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.GB_main_debug)
        self.groupBox_14.setMinimumSize(QtCore.QSize(470, 0))
        self.groupBox_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_img_left = QtWidgets.QLabel(self.groupBox_14)
        self.label_img_left.setMinimumSize(QtCore.QSize(240, 170))
        self.label_img_left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img_left.setAutoFillBackground(True)
        self.label_img_left.setText("")
        self.label_img_left.setObjectName("label_img_left")
        self.gridLayout_12.addWidget(self.label_img_left, 0, 0, 1, 1)
        self.label_img_right = QtWidgets.QLabel(self.groupBox_14)
        self.label_img_right.setMinimumSize(QtCore.QSize(240, 170))
        self.label_img_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img_right.setAutoFillBackground(True)
        self.label_img_right.setText("")
        self.label_img_right.setObjectName("label_img_right")
        self.gridLayout_12.addWidget(self.label_img_right, 0, 1, 1, 1)
        self.label_img_top = QtWidgets.QLabel(self.groupBox_14)
        self.label_img_top.setMinimumSize(QtCore.QSize(240, 170))
        self.label_img_top.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img_top.setAutoFillBackground(True)
        self.label_img_top.setText("")
        self.label_img_top.setObjectName("label_img_top")
        self.gridLayout_12.addWidget(self.label_img_top, 1, 0, 1, 1)
        self.label_img_right_2 = QtWidgets.QLabel(self.groupBox_14)
        self.label_img_right_2.setMinimumSize(QtCore.QSize(240, 170))
        self.label_img_right_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img_right_2.setAutoFillBackground(True)
        self.label_img_right_2.setText("")
        self.label_img_right_2.setObjectName("label_img_right_2")
        self.gridLayout_12.addWidget(self.label_img_right_2, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_14, 0, 1, 1, 1)
        self.gridLayout_15.setColumnStretch(0, 4)
        self.gridLayout_15.setColumnStretch(1, 5)
        self.gridLayout_22.addWidget(self.GB_main_debug, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_panel, "")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_setting)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.groupBox_Settings = QtWidgets.QGroupBox(self.tab_setting)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Settings.setFont(font)
        self.groupBox_Settings.setTitle("")
        self.groupBox_Settings.setObjectName("groupBox_Settings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_Settings)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 267, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        self.groupBox_S_robot = QtWidgets.QGroupBox(self.groupBox_Settings)
        self.groupBox_S_robot.setMinimumSize(QtCore.QSize(0, 284))
        self.groupBox_S_robot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_S_robot.setObjectName("groupBox_S_robot")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_S_robot)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_S_robot)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.LE_settings_leftIP = QtWidgets.QLineEdit(self.groupBox_6)
        self.LE_settings_leftIP.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_leftIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_leftIP.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_leftIP.setObjectName("LE_settings_leftIP")
        self.gridLayout_7.addWidget(self.LE_settings_leftIP, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setMinimumSize(QtCore.QSize(60, 25))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_safeA = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_safeA.setObjectName("groupBox_safeA")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_safeA)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.LE_settings_safeA_left_xmin = QtWidgets.QLineEdit(self.groupBox_safeA)
        self.LE_settings_safeA_left_xmin.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_left_xmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_left_xmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_left_xmin.setObjectName("LE_settings_safeA_left_xmin")
        self.gridLayout_8.addWidget(self.LE_settings_safeA_left_xmin, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_safeA)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 2, 1, 1)
        self.LE_settings_safeA_left_xmax = QtWidgets.QLineEdit(self.groupBox_safeA)
        self.LE_settings_safeA_left_xmax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_left_xmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_left_xmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_left_xmax.setObjectName("LE_settings_safeA_left_xmax")
        self.gridLayout_8.addWidget(self.LE_settings_safeA_left_xmax, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_safeA)
        self.label_9.setMinimumSize(QtCore.QSize(60, 25))
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.LE_settings_safeA_left_ymin = QtWidgets.QLineEdit(self.groupBox_safeA)
        self.LE_settings_safeA_left_ymin.setMinimumSize(QtCore.QSize(25, 0))
        self.LE_settings_safeA_left_ymin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_left_ymin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_left_ymin.setObjectName("LE_settings_safeA_left_ymin")
        self.gridLayout_8.addWidget(self.LE_settings_safeA_left_ymin, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_safeA)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 1, 2, 1, 1)
        self.LE_settings_safeA_left_ymax = QtWidgets.QLineEdit(self.groupBox_safeA)
        self.LE_settings_safeA_left_ymax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_left_ymax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_left_ymax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_left_ymax.setObjectName("LE_settings_safeA_left_ymax")
        self.gridLayout_8.addWidget(self.LE_settings_safeA_left_ymax, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_safeA)
        self.label_10.setMinimumSize(QtCore.QSize(60, 25))
        self.label_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 2, 0, 1, 1)
        self.LE_settings_safeA_left_zmin = QtWidgets.QLineEdit(self.groupBox_safeA)
        self.LE_settings_safeA_left_zmin.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_left_zmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_left_zmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_left_zmin.setObjectName("LE_settings_safeA_left_zmin")
        self.gridLayout_8.addWidget(self.LE_settings_safeA_left_zmin, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_safeA)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 2, 2, 1, 1)
        self.LE_settings_safeA_left_zmax = QtWidgets.QLineEdit(self.groupBox_safeA)
        self.LE_settings_safeA_left_zmax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_left_zmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_left_zmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_left_zmax.setObjectName("LE_settings_safeA_left_zmax")
        self.gridLayout_8.addWidget(self.LE_settings_safeA_left_zmax, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_safeA)
        self.label_14.setMinimumSize(QtCore.QSize(60, 25))
        self.label_14.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_safeA, 1, 0, 1, 1)
        self.groupBox_S_gripper = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_S_gripper.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_S_gripper.setObjectName("groupBox_S_gripper")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_S_gripper)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox_S_gripper)
        self.label_18.setMinimumSize(QtCore.QSize(60, 25))
        self.label_18.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_18.setObjectName("label_18")
        self.gridLayout_14.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_S_gripper)
        self.label_19.setMinimumSize(QtCore.QSize(0, 25))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_19.setObjectName("label_19")
        self.gridLayout_14.addWidget(self.label_19, 0, 2, 1, 1)
        self.LE_settings_gripper_left_pmax = QtWidgets.QLineEdit(self.groupBox_S_gripper)
        self.LE_settings_gripper_left_pmax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_gripper_left_pmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_gripper_left_pmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_gripper_left_pmax.setObjectName("LE_settings_gripper_left_pmax")
        self.gridLayout_14.addWidget(self.LE_settings_gripper_left_pmax, 0, 3, 1, 1)
        self.LE_settings_gripper_left_pmin = QtWidgets.QLineEdit(self.groupBox_S_gripper)
        self.LE_settings_gripper_left_pmin.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_gripper_left_pmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_gripper_left_pmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_gripper_left_pmin.setObjectName("LE_settings_gripper_left_pmin")
        self.gridLayout_14.addWidget(self.LE_settings_gripper_left_pmin, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_S_gripper, 2, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_S_robot)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_safeA_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_safeA_2.setObjectName("groupBox_safeA_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_safeA_2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_34 = QtWidgets.QLabel(self.groupBox_safeA_2)
        self.label_34.setMinimumSize(QtCore.QSize(60, 25))
        self.label_34.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_34.setObjectName("label_34")
        self.gridLayout_25.addWidget(self.label_34, 2, 0, 1, 1)
        self.LE_settings_safeA_right_zmax = QtWidgets.QLineEdit(self.groupBox_safeA_2)
        self.LE_settings_safeA_right_zmax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_right_zmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_right_zmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_right_zmax.setObjectName("LE_settings_safeA_right_zmax")
        self.gridLayout_25.addWidget(self.LE_settings_safeA_right_zmax, 2, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_safeA_2)
        self.label_33.setMinimumSize(QtCore.QSize(0, 25))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_33.setObjectName("label_33")
        self.gridLayout_25.addWidget(self.label_33, 1, 2, 1, 1)
        self.LE_settings_safeA_right_ymax = QtWidgets.QLineEdit(self.groupBox_safeA_2)
        self.LE_settings_safeA_right_ymax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_right_ymax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_right_ymax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_right_ymax.setObjectName("LE_settings_safeA_right_ymax")
        self.gridLayout_25.addWidget(self.LE_settings_safeA_right_ymax, 1, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_safeA_2)
        self.label_36.setMinimumSize(QtCore.QSize(60, 25))
        self.label_36.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_36.setObjectName("label_36")
        self.gridLayout_25.addWidget(self.label_36, 0, 0, 1, 1)
        self.LE_settings_safeA_right_ymin = QtWidgets.QLineEdit(self.groupBox_safeA_2)
        self.LE_settings_safeA_right_ymin.setMinimumSize(QtCore.QSize(25, 0))
        self.LE_settings_safeA_right_ymin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_right_ymin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_right_ymin.setObjectName("LE_settings_safeA_right_ymin")
        self.gridLayout_25.addWidget(self.LE_settings_safeA_right_ymin, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_safeA_2)
        self.label_35.setMinimumSize(QtCore.QSize(0, 25))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_35.setObjectName("label_35")
        self.gridLayout_25.addWidget(self.label_35, 2, 2, 1, 1)
        self.LE_settings_safeA_right_xmax = QtWidgets.QLineEdit(self.groupBox_safeA_2)
        self.LE_settings_safeA_right_xmax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_right_xmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_right_xmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_right_xmax.setObjectName("LE_settings_safeA_right_xmax")
        self.gridLayout_25.addWidget(self.LE_settings_safeA_right_xmax, 0, 3, 1, 1)
        self.LE_settings_safeA_right_xmin = QtWidgets.QLineEdit(self.groupBox_safeA_2)
        self.LE_settings_safeA_right_xmin.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_right_xmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_right_xmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_right_xmin.setObjectName("LE_settings_safeA_right_xmin")
        self.gridLayout_25.addWidget(self.LE_settings_safeA_right_xmin, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_safeA_2)
        self.label_16.setMinimumSize(QtCore.QSize(0, 25))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_16.setObjectName("label_16")
        self.gridLayout_25.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_safeA_2)
        self.label_27.setMinimumSize(QtCore.QSize(60, 25))
        self.label_27.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_25.addWidget(self.label_27, 1, 0, 1, 1)
        self.LE_settings_safeA_right_zmin = QtWidgets.QLineEdit(self.groupBox_safeA_2)
        self.LE_settings_safeA_right_zmin.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_safeA_right_zmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_safeA_right_zmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_safeA_right_zmin.setObjectName("LE_settings_safeA_right_zmin")
        self.gridLayout_25.addWidget(self.LE_settings_safeA_right_zmin, 2, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_safeA_2, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.LE_settings_rightIP = QtWidgets.QLineEdit(self.groupBox_7)
        self.LE_settings_rightIP.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_rightIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_rightIP.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_rightIP.setObjectName("LE_settings_rightIP")
        self.gridLayout_24.addWidget(self.LE_settings_rightIP, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setMinimumSize(QtCore.QSize(60, 25))
        self.label_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_24.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_S_gripper_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_S_gripper_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_S_gripper_2.setObjectName("groupBox_S_gripper_2")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_S_gripper_2)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_42 = QtWidgets.QLabel(self.groupBox_S_gripper_2)
        self.label_42.setMinimumSize(QtCore.QSize(0, 25))
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_42.setObjectName("label_42")
        self.gridLayout_32.addWidget(self.label_42, 0, 2, 1, 1)
        self.LE_settings_gripper_right_pmin = QtWidgets.QLineEdit(self.groupBox_S_gripper_2)
        self.LE_settings_gripper_right_pmin.setMinimumSize(QtCore.QSize(25, 0))
        self.LE_settings_gripper_right_pmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_gripper_right_pmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_gripper_right_pmin.setObjectName("LE_settings_gripper_right_pmin")
        self.gridLayout_32.addWidget(self.LE_settings_gripper_right_pmin, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_S_gripper_2)
        self.label_43.setMinimumSize(QtCore.QSize(60, 25))
        self.label_43.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_43.setObjectName("label_43")
        self.gridLayout_32.addWidget(self.label_43, 0, 0, 1, 1)
        self.LE_settings_gripper_right_pmax = QtWidgets.QLineEdit(self.groupBox_S_gripper_2)
        self.LE_settings_gripper_right_pmax.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_gripper_right_pmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_gripper_right_pmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_gripper_right_pmax.setObjectName("LE_settings_gripper_right_pmax")
        self.gridLayout_32.addWidget(self.LE_settings_gripper_right_pmax, 0, 3, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_S_gripper_2, 2, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_S_robot, 0, 0, 3, 1)
        self.PB_settings_apply = QtWidgets.QPushButton(self.groupBox_Settings)
        self.PB_settings_apply.setMaximumSize(QtCore.QSize(79, 16777215))
        self.PB_settings_apply.setObjectName("PB_settings_apply")
        self.gridLayout_5.addWidget(self.PB_settings_apply, 2, 2, 1, 1)
        self.groupBox_computerPassW = QtWidgets.QGroupBox(self.groupBox_Settings)
        self.groupBox_computerPassW.setMaximumSize(QtCore.QSize(250, 104))
        self.groupBox_computerPassW.setObjectName("groupBox_computerPassW")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_computerPassW)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_computerPassW)
        self.label_2.setMinimumSize(QtCore.QSize(63, 0))
        self.label_2.setMaximumSize(QtCore.QSize(63, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.LE_settings_comPassW = QtWidgets.QLineEdit(self.groupBox_computerPassW)
        self.LE_settings_comPassW.setMinimumSize(QtCore.QSize(0, 25))
        self.LE_settings_comPassW.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_settings_comPassW.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_settings_comPassW.setObjectName("LE_settings_comPassW")
        self.gridLayout_4.addWidget(self.LE_settings_comPassW, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_computerPassW, 0, 1, 1, 2)
        self.gridLayout_28.addWidget(self.groupBox_Settings, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_setting, "")
        self.tab_dataset = QtWidgets.QWidget()
        self.tab_dataset.setObjectName("tab_dataset")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.tab_dataset)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_dataset)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_20.setObjectName("gridLayout_20")
        spacerItem3 = QtWidgets.QSpacerItem(222, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 141, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem4, 1, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.PB_dataprocess_openDir = QtWidgets.QPushButton(self.groupBox_10)
        self.PB_dataprocess_openDir.setObjectName("PB_dataprocess_openDir")
        self.gridLayout_18.addWidget(self.PB_dataprocess_openDir, 0, 0, 1, 1)
        self.LE_dataset_dir_name = QtWidgets.QLineEdit(self.groupBox_10)
        self.LE_dataset_dir_name.setMinimumSize(QtCore.QSize(0, 29))
        self.LE_dataset_dir_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LE_dataset_dir_name.setText("")
        self.LE_dataset_dir_name.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_dataset_dir_name.setReadOnly(True)
        self.LE_dataset_dir_name.setObjectName("LE_dataset_dir_name")
        self.gridLayout_18.addWidget(self.LE_dataset_dir_name, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setMinimumSize(QtCore.QSize(0, 25))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 1, 0, 1, 1)
        self.CB_dataset_make_video = QtWidgets.QComboBox(self.groupBox_10)
        self.CB_dataset_make_video.setObjectName("CB_dataset_make_video")
        self.CB_dataset_make_video.addItem("")
        self.CB_dataset_make_video.addItem("")
        self.gridLayout_18.addWidget(self.CB_dataset_make_video, 1, 1, 1, 1)
        self.PB_dataset_confirm = QtWidgets.QPushButton(self.groupBox_10)
        self.PB_dataset_confirm.setObjectName("PB_dataset_confirm")
        self.gridLayout_18.addWidget(self.PB_dataset_confirm, 2, 1, 1, 1)
        self.gridLayout_18.setColumnStretch(0, 1)
        self.gridLayout_18.setColumnStretch(1, 2)
        self.gridLayout_20.addWidget(self.groupBox_10, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_33.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_dataset, "")
        self.gridLayout_3.addWidget(self.tabWidget_main, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMain = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionMain.setFont(font)
        self.actionMain.setObjectName("actionMain")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionSettings.setFont(font)
        self.actionSettings.setObjectName("actionSettings")
        self.actiondebug = QtWidgets.QAction(MainWindow)
        self.actiondebug.setObjectName("actiondebug")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionDebug = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionDebug.setFont(font)
        self.actionDebug.setObjectName("actionDebug")
        self.actionProcess_data = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionProcess_data.setFont(font)
        self.actionProcess_data.setObjectName("actionProcess_data")
        self.actionManual = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.actionManual.setFont(font)
        self.actionManual.setObjectName("actionManual")
        self.actionInference = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionInference.setFont(font)
        self.actionInference.setObjectName("actionInference")
        self.actionTrain = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionTrain.setFont(font)
        self.actionTrain.setObjectName("actionTrain")
        self.actionCalibration = QtWidgets.QAction(MainWindow)
        self.actionCalibration.setObjectName("actionCalibration")

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_control.setCurrentIndex(0)
        self.PB_main_enableRobot.clicked['bool'].connect(MainWindow.slot_main_PB_enableRobot)
        self.PB_main_enableCamera.clicked.connect(MainWindow.slot_main_PB_enableCamera)
        self.PB_main_enableMainhand.clicked.connect(MainWindow.slot_main_PB_enableMainhand)
        self.PB_main_start.clicked.connect(MainWindow.slot_main_PB_Start)
        self.PB_main_stop.clicked.connect(MainWindow.slot_main_PB_Stop)
        self.PB_debug_robot_getangle.clicked.connect(MainWindow.slot_debug_rob_getangle)
        self.PB_debug_robot_light.clicked.connect(MainWindow.slot_debug_rob_light)
        self.PB_debug_gripper_control.clicked.connect(MainWindow.slot_debug_gripper_open)
        self.PB_debug_cam_search.clicked.connect(MainWindow.slot_debug_cam_searchID)
        self.PB_debug_cam_confirm.clicked.connect(MainWindow.slot_debug_cam_comfirmID)
        self.PB_debug_calibration_confirm.clicked.connect(MainWindow.slot_debug_calibration_confirm)
        self.PB_settings_apply.clicked.connect(MainWindow.slot_settings_para_apply)
        self.checkB_robot_falling_protection.stateChanged['int'].connect(MainWindow.slot_main_cb_safety_protection)
        self.checkB_sensor_protection.stateChanged['int'].connect(MainWindow.slot_main_cb_sensor_protection)
        self.checkB_show_img.stateChanged['int'].connect(MainWindow.slot_main_cb_show_img)
        self.PB_dataprocess_openDir.clicked.connect(MainWindow.slot_dataset_PB_open_dir)
        self.PB_dataset_confirm.clicked.connect(MainWindow.slot_dataset_PB_transform_confirm)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Enable"))
        self.PB_main_enableCamera.setText(_translate("MainWindow", "Camera"))
        self.PB_main_enableRobot.setText(_translate("MainWindow", "Robot"))
        self.PB_main_enableMainhand.setText(_translate("MainWindow", "Hand"))
        self.label_24.setText(_translate("MainWindow", "Robot:"))
        self.label_25.setText(_translate("MainWindow", "Camera:"))
        self.label_26.setText(_translate("MainWindow", "Main hand:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Log"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Manuplation"))
        self.groupBox_select.setTitle(_translate("MainWindow", "Select"))
        self.checkB_show_img.setText(_translate("MainWindow", "Show img"))
        self.checkB_sensor_protection.setText(_translate("MainWindow", "Sensor protection"))
        self.checkB_robot_falling_protection.setText(_translate("MainWindow", "Safety protection"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.label.setText(_translate("MainWindow", "Task name:"))
        self.LE_task_name.setText(_translate("MainWindow", "Clean_dish"))
        self.PB_main_start.setText(_translate("MainWindow", "Start"))
        self.PB_main_stop.setText(_translate("MainWindow", "Stop"))
        self.tabWidget_control.setTabText(self.tabWidget_control.indexOf(self.tab_control), _translate("MainWindow", "Control"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Robot"))
        self.label_32.setText(_translate("MainWindow", "Test:"))
        self.CB_debug_robot_light.setItemText(0, _translate("MainWindow", "red"))
        self.CB_debug_robot_light.setItemText(1, _translate("MainWindow", "yellow"))
        self.CB_debug_robot_light.setItemText(2, _translate("MainWindow", "green"))
        self.CB_debug_robot_light.setItemText(3, _translate("MainWindow", "black"))
        self.label_37.setText(_translate("MainWindow", "Set Light:"))
        self.PB_debug_robot_light.setText(_translate("MainWindow", "Confirm"))
        self.PB_debug_robot_getangle.setText(_translate("MainWindow", "Get Angle"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Gripper"))
        self.label_30.setText(_translate("MainWindow", "Control"))
        self.PB_debug_gripper_control.setText(_translate("MainWindow", "Open"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Camera"))
        self.PB_debug_cam_search.setText(_translate("MainWindow", "Search"))
        self.label_31.setText(_translate("MainWindow", "Set to:"))
        self.PB_debug_cam_confirm.setText(_translate("MainWindow", "Comfirm"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Calibration"))
        self.PB_debug_calibration_confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_38.setText(_translate("MainWindow", "Calibration:"))
        self.tabWidget_control.setTabText(self.tabWidget_control.indexOf(self.tab_debug), _translate("MainWindow", "Debug"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Image"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_panel), _translate("MainWindow", "Panel"))
        self.groupBox_S_robot.setTitle(_translate("MainWindow", "Robot"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Left robot"))
        self.groupBox_6.setTitle(_translate("MainWindow", "IP Adress"))
        self.LE_settings_leftIP.setText(_translate("MainWindow", "192.168.5.1"))
        self.label_6.setText(_translate("MainWindow", "Left IP"))
        self.groupBox_safeA.setTitle(_translate("MainWindow", "Safe Area"))
        self.LE_settings_safeA_left_xmin.setText(_translate("MainWindow", "-410"))
        self.label_11.setText(_translate("MainWindow", "~"))
        self.LE_settings_safeA_left_xmax.setText(_translate("MainWindow", "210"))
        self.label_9.setText(_translate("MainWindow", "Y:"))
        self.LE_settings_safeA_left_ymin.setText(_translate("MainWindow", "-700"))
        self.label_12.setText(_translate("MainWindow", "~"))
        self.LE_settings_safeA_left_ymax.setText(_translate("MainWindow", "-210"))
        self.label_10.setText(_translate("MainWindow", "Z:"))
        self.LE_settings_safeA_left_zmin.setText(_translate("MainWindow", "47"))
        self.label_13.setText(_translate("MainWindow", "~"))
        self.LE_settings_safeA_left_zmax.setText(_translate("MainWindow", "1000"))
        self.label_14.setText(_translate("MainWindow", "X:"))
        self.groupBox_S_gripper.setTitle(_translate("MainWindow", "Gripper"))
        self.label_18.setText(_translate("MainWindow", "Pos:"))
        self.label_19.setText(_translate("MainWindow", "~"))
        self.LE_settings_gripper_left_pmax.setText(_translate("MainWindow", "3052"))
        self.LE_settings_gripper_left_pmin.setText(_translate("MainWindow", "2048"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Right robot"))
        self.groupBox_safeA_2.setTitle(_translate("MainWindow", "Safe Area"))
        self.label_34.setText(_translate("MainWindow", "Z:"))
        self.LE_settings_safeA_right_zmax.setText(_translate("MainWindow", "1000"))
        self.label_33.setText(_translate("MainWindow", "~"))
        self.LE_settings_safeA_right_ymax.setText(_translate("MainWindow", "-210"))
        self.label_36.setText(_translate("MainWindow", "X:"))
        self.LE_settings_safeA_right_ymin.setText(_translate("MainWindow", "-700"))
        self.label_35.setText(_translate("MainWindow", "~"))
        self.LE_settings_safeA_right_xmax.setText(_translate("MainWindow", "410"))
        self.LE_settings_safeA_right_xmin.setText(_translate("MainWindow", "-210"))
        self.label_16.setText(_translate("MainWindow", "~"))
        self.label_27.setText(_translate("MainWindow", "Y:"))
        self.LE_settings_safeA_right_zmin.setText(_translate("MainWindow", "47"))
        self.groupBox_7.setTitle(_translate("MainWindow", "IP Adress"))
        self.LE_settings_rightIP.setText(_translate("MainWindow", "192.168.5.2"))
        self.label_15.setText(_translate("MainWindow", "Right IP"))
        self.groupBox_S_gripper_2.setTitle(_translate("MainWindow", "Gripper"))
        self.label_42.setText(_translate("MainWindow", "~"))
        self.LE_settings_gripper_right_pmin.setText(_translate("MainWindow", "2048"))
        self.label_43.setText(_translate("MainWindow", "Pos:"))
        self.LE_settings_gripper_right_pmax.setText(_translate("MainWindow", "1044"))
        self.PB_settings_apply.setText(_translate("MainWindow", "Apply"))
        self.groupBox_computerPassW.setTitle(_translate("MainWindow", "Computer password"))
        self.label_2.setText(_translate("MainWindow", "Passw:"))
        self.LE_settings_comPassW.setText(_translate("MainWindow", "A12345"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_setting), _translate("MainWindow", "Settings"))
        self.groupBox_10.setTitle(_translate("MainWindow", "To train format"))
        self.PB_dataprocess_openDir.setText(_translate("MainWindow", "Open Dir:"))
        self.label_22.setText(_translate("MainWindow", "Make video:"))
        self.CB_dataset_make_video.setItemText(0, _translate("MainWindow", "yes"))
        self.CB_dataset_make_video.setItemText(1, _translate("MainWindow", "no"))
        self.PB_dataset_confirm.setText(_translate("MainWindow", "Confirm"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_dataset), _translate("MainWindow", "DataProcess"))
        self.actionMain.setText(_translate("MainWindow", "Main"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actiondebug.setText(_translate("MainWindow", "Debug"))
        self.action.setText(_translate("MainWindow", "Dataset"))
        self.actionDebug.setText(_translate("MainWindow", "Debug"))
        self.actionProcess_data.setText(_translate("MainWindow", "Process data"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionInference.setText(_translate("MainWindow", "Inference"))
        self.actionTrain.setText(_translate("MainWindow", "Train"))
        self.actionCalibration.setText(_translate("MainWindow", "Calibration"))
